"""empty message

Revision ID: 1b5cd9a60ce1
Revises: 50de901573c9
Create Date: 2020-08-04 12:24:28.474086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5cd9a60ce1'
down_revision = '50de901573c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_player', sa.Column('drafted_flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('available_player', 'drafted_flag')
    # ### end Alembic commands ###
