"""empty message

Revision ID: 1bde48b248a4
Revises: 6c9369d20e66
Create Date: 2020-08-02 17:29:15.768088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bde48b248a4'
down_revision = '6c9369d20e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('venmo', sa.String(120), nullable=True))
    op.add_column('user', sa.Column('paypal', sa.String(120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'venmo')
    op.drop_column('user', 'paypal')
    # ### end Alembic commands ###
