"""empty message

Revision ID: 285d1d573148
Revises: 1b5cd9a60ce1
Create Date: 2020-08-04 14:28:30.279485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285d1d573148'
down_revision = '1b5cd9a60ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_player', sa.Column('odds_int', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('available_player', 'odds_int')
    # ### end Alembic commands ###
