"""empty message

Revision ID: 59213421de7c
Revises: 5b8b8412ebf6
Create Date: 2020-08-02 23:23:27.096601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59213421de7c'
down_revision = '5b8b8412ebf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('cut_players', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('fourth_score', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'fourth_score')
    op.drop_column('team', 'cut_players')
    # ### end Alembic commands ###
