"""empty message

Revision ID: 5b8b8412ebf6
Revises: 24972902317f
Create Date: 2020-08-02 23:19:19.858036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8b8412ebf6'
down_revision = '24972902317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['venmo'])
    op.create_unique_constraint(None, 'user', ['paypal'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
