"""empty message

Revision ID: 6c9369d20e66
Revises: 91bedc6c968d
Create Date: 2020-08-02 16:55:56.249535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9369d20e66'
down_revision = '91bedc6c968d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_for_tournament', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_for_tournament')
    # ### end Alembic commands ###
