"""empty message

Revision ID: 801fe1e538e0
Revises: f9b1714573d7
Create Date: 2020-07-30 18:34:31.186417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801fe1e538e0'
down_revision = 'f9b1714573d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_player', sa.Column('holes_remaining', sa.Integer(), nullable=True))
    op.add_column('available_player', sa.Column('r1', sa.Integer(), nullable=True))
    op.add_column('available_player', sa.Column('r2', sa.Integer(), nullable=True))
    op.add_column('available_player', sa.Column('r3', sa.Integer(), nullable=True))
    op.add_column('available_player', sa.Column('r4', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('available_player', 'r4')
    op.drop_column('available_player', 'r3')
    op.drop_column('available_player', 'r2')
    op.drop_column('available_player', 'r1')
    op.drop_column('available_player', 'holes_remaining')
    # ### end Alembic commands ###
