"""empty message

Revision ID: 91bedc6c968d
Revises: 801fe1e538e0
Create Date: 2020-07-30 22:21:32.219652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bedc6c968d'
down_revision = '801fe1e538e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_player') as batch_op:
        batch_op.create_foreign_key(['drafted_player'], 'available_player', 'DraftedPlayer', ['drafted_player'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_player') as batch_op:
        batch_op.drop_constraint('test', 'available_player', type_='foreignkey')
    # ### end Alembic commands ###
