"""empty message

Revision ID: e91f8e3a6cfa
Revises:
Create Date: 2020-07-29 18:33:11.661952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91f8e3a6cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_player', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('available_player', sa.Column('country', sa.String(75),nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('available_player', 'active')
    op.drop_column('available_player', 'country')
    # ### end Alembic commands ###
